apiVersion: v1
kind: ConfigMap
metadata:
  name: soc-portal-config
  namespace: soc-portal
data:
  # Backend configuration
  DATABASE_URL: "postgresql+asyncpg://postgres:$(POSTGRES_PASSWORD)@postgres:5432/soc_portal"
  ALGORITHM: "HS256"
  ACCESS_TOKEN_EXPIRE_MINUTES: "30"
  COOKIE_SECURE: "true"
  COOKIE_SAMESITE: "None"
  BACKEND_CORS_ORIGINS: '["https://your-domain.com"]'
  
  # Keycloak configuration
  KC_DB: "postgres"
  KC_DB_USERNAME: "keycloak"
  KC_DB_URL_HOST: "kc-postgres"
  KC_DB_URL_DATABASE: "keycloak"
  KC_DB_URL_PORT: "5432"
  KC_HTTP_ENABLED: "true"
  KC_PROXY_HEADERS: "xforwarded"
  KC_HOSTNAME_STRICT: "false"
  
  # SLA configuration
  TICKET_SLA_FIRST_HOURS: "24"
  
  # File upload configuration
  MAX_FILE_SIZE: "10485760"
  ALLOWED_FILE_TYPES: "image/jpeg,image/png,application/pdf,text/plain"






